// SPDX-License-Identifier: GPL-3.0-or-later

//! Reference plugin — falling cherry-blossom petals.
//!
//! Sibling to `veiland-particles`: that drifts dots *up*, this falls
//! textured petals *down* with sway and tumble. Each petal is one
//! textured quad sampling a small petal PNG (`assets/petal.png`,
//! generated by `scripts/make_petal.py` — ours, GPL, no external asset
//! licence). The PNG is embedded into the binary with `include_bytes!`,
//! so the plugin is self-contained: nothing to install alongside it.
//! Per-petal seeds (X, time offset, cycle, drift, spin) are
//! fixed at startup; the Y position, sway, rotation and fade are
//! recomputed every frame from the cycle phase.
//!
//! Geometry-based, one quad per petal — the rotation is baked into the
//! quad corners on the CPU so the vertex shader stays a passthrough
//! (N is small; this is cheaper than a per-draw uniform path and keeps
//! one draw call for the whole field).
//!
//! Cadence mirrors `veiland-particles`: render on `BufferReleased` so
//! the compositor's repaint rate drives the animation. See that plugin's
//! module docs.

use serde::Deserialize;
use std::time::Instant;
use veiland_plugin::{Connection, DmaBuffer, Frame, FramePacer, GbmEgl, PluginError, SyncFence};
use veiland_protocol::Buffer;

const PLUGIN_NAME: &str = "sakura";

/// Fall-cycle range per petal, in seconds. Petals fall slower and more
/// languidly than the dots rise. Each petal picks a fixed value in this
/// range at startup so the field desynchronises.
const FALL_MIN_SECONDS: f32 = 9.0;
const FALL_MAX_SECONDS: f32 = 16.0;

/// Max net horizontal drift over one fall, logical px. Signed per petal
/// so some blow left, some right (wind variance).
const DRIFT_MAX_PX: f32 = 120.0;
/// Amplitude of the gentle sideways sin-sway layered on the net drift.
const SWAY_PX: f32 = 28.0;
/// Max tumble over one fall, in full turns. Signed per petal (some spin
/// CW, some CCW). A petal makes up to this many rotations as it falls.
const SPIN_MAX_TURNS: f32 = 1.4;
/// Peak per-petal opacity. Slightly under 1 keeps petals soft.
const PEAK_OPACITY: f32 = 0.9;
/// Fraction of the fall spent fading in / out at each end.
const FADE_FRACTION: f32 = 0.1;

/// The petal texture, compiled into the binary at build time. The plugin
/// and its asset ship as one file — no external PNG to install, no path
/// to configure, no dependence on the working directory. (Snow, roses,
/// etc. would be sibling plugins, each embedding its own asset.)
const PETAL_PNG: &[u8] = include_bytes!("../assets/petal.png");

#[derive(Debug, Clone, Deserialize)]
struct Config {
    #[serde(default = "default_count")]
    count: u32,
    /// Tint multiplied into the petal texture. Default white = no tint
    /// (the PNG is already pink). Lower the alpha to fade the whole field.
    #[serde(default = "default_color")]
    color: [f32; 4],
    /// Petal half-extent in logical pixels at scale=1 (the quad is
    /// 2×this on a side). Multiplied by `Configure.scale` at render time.
    #[serde(default = "default_size_px")]
    size_px: f32,
}

fn default_count() -> u32 {
    25
}
fn default_color() -> [f32; 4] {
    [1.0, 1.0, 1.0, 1.0]
}
fn default_size_px() -> f32 {
    22.0
}

fn default_config() -> Config {
    Config {
        count: default_count(),
        color: default_color(),
        size_px: default_size_px(),
    }
}

fn load_config() -> Config {
    match std::env::var("VEILAND_PLUGIN_CONFIG") {
        Ok(s) => match serde_json::from_str::<Config>(&s) {
            Ok(c) => c,
            Err(e) => {
                eprintln!(
                    "veiland-{}: failed to parse VEILAND_PLUGIN_CONFIG as JSON: {} \
                     — falling back to defaults",
                    PLUGIN_NAME, e
                );
                default_config()
            }
        },
        Err(_) => {
            eprintln!(
                "veiland-{}: VEILAND_PLUGIN_CONFIG unset — using defaults",
                PLUGIN_NAME
            );
            default_config()
        }
    }
}

/// Per-petal constants, randomised once at startup and fixed for life.
#[derive(Clone, Copy)]
struct Petal {
    x_norm: f32,
    t_offset: f32,
    cycle: f32,
    /// Net horizontal drift over the fall, logical px (signed).
    drift_px: f32,
    /// Sway phase offset so petals don't sway in unison.
    sway_phase: f32,
    /// Tumble: starting rotation (rad) and total spin over the fall (rad,
    /// signed).
    rot0: f32,
    spin: f32,
}

/// Tiny deterministic PRNG (xorshift32), same as veiland-particles — a
/// hashed stagger is plenty for seeding a decorative field.
struct Rng(u32);
impl Rng {
    fn next_f32(&mut self) -> f32 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 17;
        x ^= x << 5;
        self.0 = x.max(1);
        (x >> 8) as f32 / (1u32 << 24) as f32
    }
}

fn seed_petals(count: u32) -> Vec<Petal> {
    let mut rng = Rng(0x1234_5678);
    (0..count)
        .map(|_| {
            let cycle = FALL_MIN_SECONDS + rng.next_f32() * (FALL_MAX_SECONDS - FALL_MIN_SECONDS);
            Petal {
                x_norm: rng.next_f32(),
                t_offset: rng.next_f32() * cycle,
                cycle,
                drift_px: (rng.next_f32() * 2.0 - 1.0) * DRIFT_MAX_PX,
                sway_phase: rng.next_f32() * std::f32::consts::TAU,
                rot0: rng.next_f32() * std::f32::consts::TAU,
                spin: (rng.next_f32() * 2.0 - 1.0) * SPIN_MAX_TURNS * std::f32::consts::TAU,
            }
        })
        .collect()
}

unsafe fn compile_shader(kind: gl::types::GLenum, src: &[u8]) -> gl::types::GLuint {
    unsafe {
        let shader = gl::CreateShader(kind);
        let src_ptr = src.as_ptr() as *const _;
        gl::ShaderSource(shader, 1, &src_ptr, std::ptr::null());
        gl::CompileShader(shader);
        let mut ok: gl::types::GLint = 0;
        gl::GetShaderiv(shader, gl::COMPILE_STATUS, &mut ok);
        if ok == 0 {
            let mut log = [0u8; 1024];
            let mut len: gl::types::GLsizei = 0;
            gl::GetShaderInfoLog(
                shader,
                log.len() as i32,
                &mut len,
                log.as_mut_ptr() as *mut _,
            );
            panic!(
                "shader compile failed: {}",
                std::str::from_utf8(&log[..len as usize]).unwrap_or("<invalid utf8>")
            );
        }
        shader
    }
}

unsafe fn link_program(vs: gl::types::GLuint, fs: gl::types::GLuint) -> gl::types::GLuint {
    unsafe {
        let program = gl::CreateProgram();
        gl::AttachShader(program, vs);
        gl::AttachShader(program, fs);
        gl::LinkProgram(program);
        let mut ok: gl::types::GLint = 0;
        gl::GetProgramiv(program, gl::LINK_STATUS, &mut ok);
        if ok == 0 {
            let mut log = [0u8; 1024];
            let mut len: gl::types::GLsizei = 0;
            gl::GetProgramInfoLog(
                program,
                log.len() as i32,
                &mut len,
                log.as_mut_ptr() as *mut _,
            );
            panic!(
                "program link failed: {}",
                std::str::from_utf8(&log[..len as usize]).unwrap_or("<invalid utf8>")
            );
        }
        program
    }
}

/// Decode the embedded petal PNG to RGBA8. Returns None (logged) on decode
/// failure — a corrupt build must not crash the locker; render() then draws
/// nothing.
fn load_petal_rgba() -> Option<(u32, u32, Vec<u8>)> {
    let img = match image::load_from_memory_with_format(PETAL_PNG, image::ImageFormat::Png) {
        Ok(i) => i,
        Err(e) => {
            eprintln!(
                "veiland-{}: failed to decode embedded petal PNG: {}",
                PLUGIN_NAME, e
            );
            return None;
        }
    };
    let rgba = img.to_rgba8();
    let (w, h) = (rgba.width(), rgba.height());
    eprintln!(
        "veiland-{}: loaded embedded petal as {}x{} RGBA",
        PLUGIN_NAME, w, h
    );
    Some((w, h, rgba.into_raw()))
}

struct GpuState {
    program: gl::types::GLuint,
    vbo: gl::types::GLuint,
    /// 0 if the petal texture failed to load — render() skips drawing.
    texture: gl::types::GLuint,
    a_pos_loc: gl::types::GLuint,
    a_uv_loc: gl::types::GLuint,
    a_fade_loc: gl::types::GLuint,
    u_color_loc: gl::types::GLint,
    u_tex_loc: gl::types::GLint,
}

/// Build the shader, VBO, and upload the petal texture.
///
/// Per vertex: `a_pos` (clip-space, rotation already baked in), `a_uv`
/// (petal texture coords 0..1), `a_fade` (per-petal opacity). 5 floats,
/// 6 verts/petal.
unsafe fn build_gpu_state() -> GpuState {
    let vs_src = b"#version 100\n\
        attribute vec2 a_pos;\n\
        attribute vec2 a_uv;\n\
        attribute float a_fade;\n\
        varying vec2 v_uv;\n\
        varying float v_fade;\n\
        void main() {\n\
            v_uv = a_uv;\n\
            v_fade = a_fade;\n\
            gl_Position = vec4(a_pos, 0.0, 1.0);\n\
        }\n\0";

    // Sample the petal texture, tint by u_color, fade by the per-petal
    // alpha, and emit premultiplied (the host composites this dmabuf with
    // glBlendFunc(ONE, 1-SRC_ALPHA)).
    let fs_src = b"#version 100\n\
        precision mediump float;\n\
        varying vec2 v_uv;\n\
        varying float v_fade;\n\
        uniform sampler2D u_tex;\n\
        uniform vec4 u_color;\n\
        void main() {\n\
            vec4 texel = texture2D(u_tex, v_uv);\n\
            float a = texel.a * u_color.a * v_fade;\n\
            if (a <= 0.0) discard;\n\
            vec3 rgb = texel.rgb * u_color.rgb;\n\
            gl_FragColor = vec4(rgb * a, a);\n\
        }\n\0";

    unsafe {
        let vs = compile_shader(gl::VERTEX_SHADER, vs_src);
        let fs = compile_shader(gl::FRAGMENT_SHADER, fs_src);
        let program = link_program(vs, fs);
        gl::UseProgram(program);

        let mut vbo: gl::types::GLuint = 0;
        gl::GenBuffers(1, &mut vbo);
        gl::BindBuffer(gl::ARRAY_BUFFER, vbo);

        // Upload the petal texture (0 on failure → render() skips).
        let texture = match load_petal_rgba() {
            Some((w, h, rgba)) => {
                let mut tex: gl::types::GLuint = 0;
                gl::GenTextures(1, &mut tex);
                gl::BindTexture(gl::TEXTURE_2D, tex);
                gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_MIN_FILTER, gl::LINEAR as i32);
                gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_MAG_FILTER, gl::LINEAR as i32);
                gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_WRAP_S, gl::CLAMP_TO_EDGE as i32);
                gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_WRAP_T, gl::CLAMP_TO_EDGE as i32);
                gl::TexImage2D(
                    gl::TEXTURE_2D,
                    0,
                    gl::RGBA as i32,
                    w as i32,
                    h as i32,
                    0,
                    gl::RGBA,
                    gl::UNSIGNED_BYTE,
                    rgba.as_ptr() as *const _,
                );
                tex
            }
            None => 0,
        };

        let a_pos_loc = gl::GetAttribLocation(program, c"a_pos".as_ptr()) as gl::types::GLuint;
        let a_uv_loc = gl::GetAttribLocation(program, c"a_uv".as_ptr()) as gl::types::GLuint;
        let a_fade_loc = gl::GetAttribLocation(program, c"a_fade".as_ptr()) as gl::types::GLuint;
        let u_color_loc = gl::GetUniformLocation(program, c"u_color".as_ptr());
        let u_tex_loc = gl::GetUniformLocation(program, c"u_tex".as_ptr());

        GpuState {
            program,
            vbo,
            texture,
            a_pos_loc,
            a_uv_loc,
            a_fade_loc,
            u_color_loc,
            u_tex_loc,
        }
    }
}

struct State {
    config: Config,
    petals: Vec<Petal>,
    /// CPU-side vertex buffer. 6 verts/petal × 5 floats/vert.
    cpu_verts: Vec<f32>,
    scale_120: u32,
    start: Instant,
}

/// Pixel-space (origin top-left, Y down) → clip-space, matching the
/// other plugins' "no Y flip" convention (the host composites row 0 at
/// the top of the screen).
fn px_to_clip(x: f32, y: f32, w: f32, h: f32) -> (f32, f32) {
    let cx = (x / w) * 2.0 - 1.0;
    let cy = (y / h) * 2.0 - 1.0;
    (cx, cy)
}

/// Fill `cpu_verts` for every petal: falling Y, sway X, tumble rotation
/// baked into the corners, and the fade alpha. Called per frame.
fn update_vertices(state: &mut State, surface_w: u32, surface_h: u32) {
    let now = state.start.elapsed().as_secs_f32();
    let w = surface_w as f32;
    let h = surface_h as f32;
    let scale = state.scale_120 as f32 / 120.0;
    let r = state.config.size_px * scale;

    // The four corner offsets of the unrotated petal quad, with their UVs.
    // (lx, ly, u, v). UV: u left→right 0..1, v top→bottom 0..1 — the petal
    // PNG's tip is at the top (v=0), matching how it was authored.
    let corners = [
        (-r, -r, 0.0, 0.0), // top-left
        (r, -r, 1.0, 0.0),  // top-right
        (-r, r, 0.0, 1.0),  // bottom-left
        (r, r, 1.0, 1.0),   // bottom-right
    ];

    for (i, p) in state.petals.iter().enumerate() {
        let phase = ((now + p.t_offset) % p.cycle) / p.cycle;

        // Falling: phase 0 = just above the buffer (y = -r), phase 1 =
        // just below (y = h + r).
        let cy_px = -r + phase * (h + 2.0 * r);
        let drift = p.drift_px * scale * phase;
        let sway = SWAY_PX * scale * (phase * std::f32::consts::TAU + p.sway_phase).sin();
        let cx_px = p.x_norm * w + drift + sway;

        // Tumble: rotate the corners around the petal centre.
        let angle = p.rot0 + p.spin * phase;
        let (sin_a, cos_a) = angle.sin_cos();

        // Fade in/out at the travel ends.
        let fade = if phase < FADE_FRACTION {
            phase / FADE_FRACTION
        } else if phase > 1.0 - FADE_FRACTION {
            (1.0 - phase) / FADE_FRACTION
        } else {
            1.0
        };
        let alpha = fade.clamp(0.0, 1.0) * PEAK_OPACITY;

        // Build the 6 vertices (two triangles: TL,BL,TR and TR,BL,BR).
        // For each corner, rotate the local offset then place at centre.
        let mut clip = [(0.0f32, 0.0f32); 4];
        for (c, &(lx, ly, _, _)) in corners.iter().enumerate() {
            let rx = lx * cos_a - ly * sin_a;
            let ry = lx * sin_a + ly * cos_a;
            clip[c] = px_to_clip(cx_px + rx, cy_px + ry, w, h);
        }

        let order = [0usize, 2, 1, 1, 2, 3]; // TL,BL,TR, TR,BL,BR
        let off = i * 6 * 5;
        for (k, &ci) in order.iter().enumerate() {
            let (px, py) = clip[ci];
            let (_, _, u, v) = corners[ci];
            let o = off + k * 5;
            state.cpu_verts[o] = px;
            state.cpu_verts[o + 1] = py;
            state.cpu_verts[o + 2] = u;
            state.cpu_verts[o + 3] = v;
            state.cpu_verts[o + 4] = alpha;
        }
    }
}

fn run() -> Result<(), PluginError> {
    eprintln!(
        "veiland-{} (pid {}) starting",
        PLUGIN_NAME,
        std::process::id()
    );

    let config = load_config();
    eprintln!(
        "veiland-{}: config count={} color={:?} size_px={}",
        PLUGIN_NAME, config.count, config.color, config.size_px
    );

    let gbm_egl = GbmEgl::new()?;

    // Connect preamble (from_env + handshake + hello) in one call.
    let mut conn = Connection::connect(PLUGIN_NAME, env!("CARGO_PKG_VERSION"))?;
    eprintln!("connected to host, hello sent");

    let fast_path = conn.host_supports_fence_fd() && gbm_egl.supports_fence_fd();
    eprintln!(
        "sync model: {} (host_cap={}, plugin_cap={})",
        if fast_path {
            "fast (fence fd)"
        } else {
            "slow (glFinish)"
        },
        conn.host_supports_fence_fd(),
        gbm_egl.supports_fence_fd(),
    );

    let first_configure = match conn.wait_for_configure()? {
        Some(c) => c,
        None => {
            eprintln!("veiland-{}: shutdown before first configure", PLUGIN_NAME);
            return Ok(());
        }
    };
    eprintln!(
        "veiland-{}: first configure region=({},{}) {}x{} scale_120={}",
        PLUGIN_NAME,
        first_configure.region_x,
        first_configure.region_y,
        first_configure.region_w,
        first_configure.region_h,
        first_configure.scale_120,
    );

    let mut dma = DmaBuffer::new(&gbm_egl, first_configure.region_w, first_configure.region_h)?;
    eprintln!(
        "allocated {}x{} {:?}, modifier=0x{:016x}, stride={}",
        dma.width(),
        dma.height(),
        dma.format(),
        u64::from(dma.modifier()),
        dma.stride(),
    );

    dma.bind_for_rendering()?;
    let gpu = unsafe { build_gpu_state() };

    let petals = seed_petals(config.count);
    let cpu_verts = vec![0.0_f32; petals.len() * 6 * 5];

    let mut state = State {
        config,
        petals,
        cpu_verts,
        scale_120: first_configure.scale_120,
        start: Instant::now(),
    };

    // Rebuilt whenever `dma` is reallocated (on a region change), since the
    // buffer carries the fd/stride/modifier the host needs to import it.
    let mut buf_msg = buffer_msg_for(&dma);

    // Self-pacing handled by FramePacer: render on BufferReleased so the
    // compositor's repaint rate drives the fall. We just react to the
    // outcomes it hands back.
    let mut pacer = FramePacer::self_paced();
    loop {
        match pacer.next(&mut conn)? {
            Frame::Render => {
                render_and_send(
                    &dma, &gbm_egl, &mut conn, &buf_msg, &gpu, &mut state, fast_path,
                )?;
                pacer.submitted();
            }
            Frame::Reconfigure(c) => {
                // Reallocate the dmabuf to the output's true size. Petal math
                // is already resolution-independent (x_norm * w, size * scale,
                // read fresh each frame), so native-size buffer = correctly
                // sized, crisp petals — no geometry change. Non-fatal on
                // failure.
                match dma.resize_to(&gbm_egl, c.region_w, c.region_h) {
                    Ok(true) => {
                        buf_msg = buffer_msg_for(&dma);
                        eprintln!(
                            "veiland-{}: reallocated to {}x{}, stride={}",
                            PLUGIN_NAME,
                            dma.width(),
                            dma.height(),
                            dma.stride(),
                        );
                    }
                    Ok(false) => {}
                    Err(e) => {
                        eprintln!(
                            "veiland-{}: reallocation to {}x{} failed: {} — \
                             keeping current buffer, petals may scale wrong",
                            PLUGIN_NAME, c.region_w, c.region_h, e
                        );
                    }
                }
                state.scale_120 = c.scale_120;
            }
            Frame::Shutdown => {
                eprintln!("host requested shutdown");
                return Ok(());
            }
        }
    }
}

/// Build the wire `Buffer` message describing `dma`. Rebuilt after any
/// reallocation, since the fd/stride/modifier move with the GBM bo. `id`
/// stays 0 — v1 is single-buffer.
fn buffer_msg_for(dma: &DmaBuffer) -> Buffer {
    Buffer {
        id: 0,
        width: dma.width(),
        height: dma.height(),
        format: dma.format(),
        modifier: dma.modifier(),
        stride: dma.stride(),
        offset: 0,
    }
}

fn render_and_send(
    dma: &DmaBuffer,
    gbm_egl: &GbmEgl,
    conn: &mut Connection,
    buf_msg: &Buffer,
    gpu: &GpuState,
    state: &mut State,
    fast_path: bool,
) -> Result<(), PluginError> {
    dma.bind_for_rendering()?;
    let (w, h) = (dma.width(), dma.height());

    update_vertices(state, w, h);

    unsafe {
        gl::Viewport(0, 0, w as i32, h as i32);
        // Transparent — petals sit on top of the wallpaper + vignette
        // via the host's z-ordered composite.
        gl::ClearColor(0.0, 0.0, 0.0, 0.0);
        gl::Clear(gl::COLOR_BUFFER_BIT);

        // Nothing to draw if the petal texture failed to load — leave the
        // buffer transparent rather than crash the locker.
        if gpu.texture != 0 {
            gl::Enable(gl::BLEND);
            // Premultiplied-alpha over operator; FS emits RGB*a.
            gl::BlendFunc(gl::ONE, gl::ONE_MINUS_SRC_ALPHA);

            gl::UseProgram(gpu.program);
            gl::ActiveTexture(gl::TEXTURE0);
            gl::BindTexture(gl::TEXTURE_2D, gpu.texture);
            gl::Uniform1i(gpu.u_tex_loc, 0);

            gl::BindBuffer(gl::ARRAY_BUFFER, gpu.vbo);
            gl::BufferData(
                gl::ARRAY_BUFFER,
                std::mem::size_of_val(&state.cpu_verts[..]) as isize,
                state.cpu_verts.as_ptr() as *const _,
                gl::STREAM_DRAW,
            );

            // 5 floats/vertex: px, py, u, v, fade.
            let stride = (5 * std::mem::size_of::<f32>()) as i32;
            gl::EnableVertexAttribArray(gpu.a_pos_loc);
            gl::VertexAttribPointer(
                gpu.a_pos_loc,
                2,
                gl::FLOAT,
                gl::FALSE,
                stride,
                std::ptr::null(),
            );
            gl::EnableVertexAttribArray(gpu.a_uv_loc);
            gl::VertexAttribPointer(
                gpu.a_uv_loc,
                2,
                gl::FLOAT,
                gl::FALSE,
                stride,
                (2 * std::mem::size_of::<f32>()) as *const _,
            );
            gl::EnableVertexAttribArray(gpu.a_fade_loc);
            gl::VertexAttribPointer(
                gpu.a_fade_loc,
                1,
                gl::FLOAT,
                gl::FALSE,
                stride,
                (4 * std::mem::size_of::<f32>()) as *const _,
            );

            gl::Uniform4f(
                gpu.u_color_loc,
                state.config.color[0],
                state.config.color[1],
                state.config.color[2],
                state.config.color[3],
            );

            gl::DrawArrays(gl::TRIANGLES, 0, (state.petals.len() * 6) as i32);
        }
    }

    if fast_path {
        unsafe {
            gl::Flush();
        }
        let fence = SyncFence::create(gbm_egl)?;
        conn.send_buffer(buf_msg, dma.dmabuf_fd(), Some(fence.as_fd()))?;
    } else {
        dma.finish();
        conn.send_buffer(buf_msg, dma.dmabuf_fd(), None)?;
    }
    Ok(())
}

fn main() {
    if let Err(e) = run() {
        eprintln!("{}: {}", env!("CARGO_PKG_NAME"), e);
        std::process::exit(1);
    }
}
